### ISSUE TITLE
It's unclear what pro/cons of ps-strongcheck are over ps-quickcheck 

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-strongcheck#57]
It would be nice to expand README by making pro/cons of ps-strongcheck over ps-quickcheck.

My only knowledge on this topic comes from [this](https://github.com/garyb/purescript-strongcheck-laws/pull/5#issuecomment-451991404) comment of @garyb
> Do you need to use strongcheck over quickcheck? QC is quite a bit faster and fully stack safe nowadays.

**Comment by JordanMartinez** [comment]
See [this page from my repo](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/21-Hello-World/05-Testing/test/03-Property-Testing-Libraries-Comparison.md).

Specifically, `garyb` stated that StrongCheck has exhaustive and statistic checking whereas QC does not. Otherwise, SC was stack-safe before QC was.
